### ISSUE TITLE
Token listing

### ISSUE THREAD

**Issue by DerArzt87** [cronaswap/cronaswap-tokenlists#13]
Hello, 
i wish you liste my Token.
0xea0a4546C3AFebcc2Bc53F3d42Ddc66fcBe7c25B
![omar2-02](https://user-images.githubusercontent.com/97561186/149027502-91111277-029d-4d48-a122-bfd54e2ac499.png)
[omar2-02.zip](https://github.com/cronaswap/cronaswap-tokenlists/files/7850116/omar2-02.zip)
 Sorry SVG file cannt uploded, i made it zip

thank you

**Comment by DerArzt87** [comment]
Hello, 
Contract is verified, I didn't yesterday, thank you

**Comment by DerArzt87** [comment]
https://cronoscan.com/address/0xea0a4546C3AFebcc2Bc53F3d42Ddc66fcBe7c25B#code

you can see that is verified

**Comment by CronaChef** [comment]
Added. pls check later.

**Comment by DerArzt87** [comment]
Thank you, but I don't see the logo, and they aren't in the Liste.

**Comment by DerArzt87** [comment]
I see it now thanks
