### ISSUE TITLE
Add CroKing to TokenList

### ISSUE THREAD

**Issue by crokingtoken** [cronaswap/cronaswap-tokenlists#16]
Hi, I want to apply for a Token Listing.

Token Address: 0x065de42e28e42d90c2052a1b49e7f83806af0e1f
![Logo102x102](https://user-images.githubusercontent.com/97338000/149657894-20de9837-825f-41fa-874e-d535fbf27efd.png)

I can't upload a svg unfortunately

Thank you :-)

**Comment by CronaChef** [comment]
Added. pls check later.
