### ISSUE TITLE
ADDING LOGO TO MY TOKEN

### ISSUE THREAD

**Issue by ObiCromax** [cronaswap/cronaswap-tokenlists#4]
token address:

0x1985127d1B21af04d09a69Cdcb1dD33fd8961e9c

token logo 102x102 PNG attached

 _(FYI) GITHUB tells me I can not attach SVG files in here, that the file is not supported, so I was not able to submit 102x102 SVG file you requested. Only the PNG file. Is there an email where I can send the SVG file? I'd be more than happy to send it to you._ 

![ICONLOGO](https://user-images.githubusercontent.com/96543881/147147062-a2fe74f5-108c-49e2-b826-f5a4f5e2e325.png)

![FILENOTSUPPORTED](https://user-images.githubusercontent.com/96543881/147148358-c82ceb8d-b841-4818-bcf1-ffa9193f3c99.png)

So here is my google drive link sharing the svg file:
https://drive.google.com/file/d/1_nNyaRmF4zurtiq38HHU-S7yhBXGIvH6/view?usp=sharing

**Comment by CronaChef** [comment]
ok guys. 

you need to create a PR not issue.

**Comment by CronaChef** [comment]
Added into.

https://github.com/cronaswap/cronaswap-tokenlists/blob/main/cronaswap-default.tokenlist.json

**Comment by CronaChef** [comment]
Next time, please read this:
https://github.com/cronaswap/cronaswap-tokenlists/blob/main/README.md

thanks!
