### ISSUE TITLE
Add Token Logo for LHRC

### ISSUE THREAD

**Issue by ccmchad** [cronaswap/cronaswap-tokenlists#9]
Token Address: 0xEfD450027bD0EE84AfaFbC75f5A80C367eFBF651
![lazyhorselogo](https://user-images.githubusercontent.com/88204337/147763413-bb12762b-ffdc-429a-9426-a6f75e6ae9ef.png)

Upload does not support SVG files.

**Comment by CronaChef** [comment]
https://github.com/cronaswap/cronaswap-tokenlists/blob/main/README.md
Pls follow this.
